#!/bin/bash
name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
height=$(jq '.height' data.json | awk '{print $1/10}')
weight=$(jq '.weight' data.json | awk '{print $1/10}')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')

echo "$name is of type $type, weighs ${weight}kg, and is ${height}m tall."
